research_task:
  description: >
    Realizar uma pesquisa aprofundada sobre os setores definidos, identificando notícias e dados relevantes em fontes abertas, com foco em portais brasileiros e algumas fontes internacionais essenciais. A pesquisa deve priorizar informações recentes e alinhadas com as seguintes palavras-chave:  
    - M&A  
    - Ameaças (Threats)  
    - Crescimento (Growth)  
    - Declínio (Decline)  
    - Dívida (Debt)  
    - Demanda de capital (Capital demand)  
    - Perspectiva (Outlook)  
    - Investimento (Investment)  
    - Consolidação (Consolidation)  
    - Tese de investimento (Thesis)  
    - Tese de desinvestimento (Divestment thesis)  
    - Alavancagem (Leverage)  

    A pesquisa deve ser limitada a informações publicadas **nos últimos 7 dias**, garantindo que o conteúdo esteja alinhado com o contexto atual de dezembro de 2024.  

    **Portais prioritários para busca:**  
    - Fontes brasileiras:  
      - Valor Econômico  
      - Exame  
      - Estadão  
      - Folha de S. Paulo  
      - O Globo  
      - G1 (Economia e Negócios)  
      - Reuters Brasil  
      - Agência Brasil  
      - Nexo Jornal  
      - CNN Brasil (Economia)  
    - Fontes internacionais (para apoio ou contexto adicional):  
      - Bloomberg  
      - Financial Times  
      - The Economist  
      - Reuters  
      - CNBC

  expected_output: >
    Uma lista de até 10 tópicos em formato de bullet points, destacando as informações mais relevantes sobre os setores definidos, apresentadas de forma clara e concisa, com referências completas às fontes utilizadas.

  agent: researcher
  inputs:
    filters:
      date_range: last_week
      language: pt
    keywords:
      - M&A
      - Threats
      - Growth
      - Decline
      - Debt
      - Capital demand
      - Outlook
      - Investment
      - Consolidation
      - Thesis
      - Divestment thesis
      - Leverage
    sources:
      - Valor Econômico
      - Exame
      - CNN Brasil
      - G1
      - Bloomberg
      - Reuters

reporting_task:
  description: >
    Revisar o contexto coletado e expandir cada ponto em uma seção detalhada para um relatório.  
    As seções devem incluir:  
    - Um resumo conciso das informações coletadas, segmentado por setor.  
    - Referências claras para as fontes utilizadas.  
    - Destaque dos tópicos mais relevantes para analistas, com foco em temas como M&A, alavancagem, consolidação e perspectivas de mercado.  
    Certifique-se de que o relatório seja baseado **apenas em notícias publicadas nos últimos 7 dias** para garantir relevância.

  expected_output: >
    Um relatório completo, com os principais tópicos e subseções detalhadas, formatado em markdown.  
    Cada seção deve incluir:  
    - Um resumo inicial.  
    - Informações adicionais.  
    - Referências completas das fontes citadas.

  agent: reporting_analyst
  configuration:
    formatting: "markdown"
    references: "mandatory" # Exige referências em todas as seções
    timeframe: "last 7 days only" # Filtrar apenas dados recentes
